import Foundation

extension Repository.Policy.Uniformity.Wave {
    /// The ratified canonical package shape policy, embedded byte-exact.
    ///
    /// Shape policy 4, ratified 2026-08-15 on swift-institute/.github#600:
    /// an absolute allowlist (439 UTF-8 bytes). `canonical()` refuses
    /// unless the embedded bytes still hash to the ratified digest, so no
    /// consumer can ship drifted bytes.
    public enum Payload {
        /// SHA-256 of the ratified bytes, exactly as recorded in the
        /// #600 ratification comment.
        public static let digest =
            "b6857f3d3eb7e78bb154e7b9155e26441d805b5a38bc212339489e30ccad161c"

        public static let bytes = Data(text.utf8)

        public static func canonical() throws(Repository.Policy.Uniformity.Wave.Error) -> Data {
            guard Repository.Policy.Caller.Wave.digest(bytes) == digest else {
                throw .verification(
                    "embedded shape policy does not hash to the ratified digest \(digest)"
                )
            }
            return bytes
        }

        private static let text = """
            # Generated by instituteci. Do not edit.
            # Canonical Swift package shape policy: 4 (absolute allowlist)

            /*
            !/.github
            !/Sources
            !/Tests
            !/Package.swift
            !/.spi.yml
            !/LICENSE.md
            !/README.md
            !/.gitignore

            /.github/*
            !/.github/workflows
            !/.github/metadata.yaml
            !/.github/FUNDING.yml
            /.github/workflows/*
            !/.github/workflows/ci.yml

            /Sources/**
            !/Sources/**/
            !/Sources/**/*.swift
            !/Sources/**/*.docc/**
            /Tests/**
            !/Tests/**/
            !/Tests/**/*.swift

            """
    }
}
