extension Repository.Policy.Metadata.Draft {
    /// The draft as the `.github/metadata.yaml` a reviewer opens.
    ///
    /// Byte-for-byte what the retired shell heredoc emitted, header
    /// comments included. The header is not decoration: it names the
    /// generator, the date, and the detected class, which is the whole
    /// audit trail a reviewer has for why the fields below say what they
    /// say — and it carries the one instruction that makes a draft a
    /// draft.
    public struct Render: Sendable, Equatable {
        /// The date the header stamps, `YYYY-MM-DD`. Supplied rather than
        /// read from the clock so a re-run of the same wave renders the
        /// same bytes and the caller's byte-compare stays meaningful.
        public let date: String

        public init(generatedOn date: String) {
            self.date = date
        }
    }
}

extension Repository.Policy.Metadata.Draft.Render {
    public func callAsFunction(_ draft: Repository.Policy.Metadata.Draft) -> String {
        var lines = [
            "# .github/metadata.yaml",
            "# Generated by swift-institute/.github generate-metadata.yml (\(date)).",
            "# Detected class: \(draft.kind.rawValue)",
            "# REVIEW BEFORE MERGE: replace any TODO entries with real values.",
            "description: \"\(draft.metadata.description)\"",
        ]
        if draft.metadata.topics.isEmpty {
            lines.append("topics: []")
        } else {
            lines.append("topics:")
            lines += draft.metadata.topics.map { "  - \($0)" }
        }
        // An empty homepage omits the key rather than asserting an empty
        // one: an organization's `.github` repository has no website, and
        // `homepage: ""` would tell `sync-metadata` to clear whatever is
        // there.
        if !draft.metadata.homepage.isEmpty {
            lines.append("homepage: \"\(draft.metadata.homepage)\"")
        }
        return lines.joined(separator: "\n") + "\n"
    }
}
