import Foundation

extension Repository.Policy.Uniformity.Wave {
    /// The ratified canonical package shape policy, embedded byte-exact.
    ///
    /// Shape policy 5, ratified on swift-institute/.github#600: an
    /// absolute allowlist (522 UTF-8 bytes). Policy 5 succeeds policy 4
    /// by admitting the C shim sources a `* Shims` target needs — `.h`,
    /// `.c`, and `.modulemap` under `Sources/* Shims/` — which policy 4's
    /// Swift-only allowlist denied. `canonical()` refuses unless the
    /// embedded bytes still hash to the ratified digest, so no consumer
    /// can ship drifted bytes.
    public enum Payload {
        /// SHA-256 of the ratified bytes, exactly as recorded in the
        /// #600 ratification comment.
        public static let digest =
            "8e37977a3b8f0a0d9e028e6089172d811eea21e6868a878ab43a1d4875df02f7"

        public static let bytes = Data(text.utf8)

        public static func canonical() throws(Repository.Policy.Uniformity.Wave.Error) -> Data {
            guard Repository.Policy.Caller.Wave.digest(bytes) == digest else {
                throw .verification(
                    "embedded shape policy does not hash to the ratified digest \(digest)"
                )
            }
            return bytes
        }

        private static let text = """
            # Generated by instituteci. Do not edit.
            # Canonical Swift package shape policy: 5 (absolute allowlist)

            /*
            !/.github
            !/Sources
            !/Tests
            !/Package.swift
            !/.spi.yml
            !/LICENSE.md
            !/README.md
            !/.gitignore

            /.github/*
            !/.github/workflows
            !/.github/metadata.yaml
            !/.github/FUNDING.yml
            /.github/workflows/*
            !/.github/workflows/ci.yml

            /Sources/**
            !/Sources/**/
            !/Sources/**/*.swift
            !/Sources/**/*.docc/**
            !/Sources/* Shims/**/*.h
            !/Sources/* Shims/**/*.c
            !/Sources/* Shims/**/*.modulemap
            /Tests/**
            !/Tests/**/
            !/Tests/**/*.swift

            """
    }
}
